### ISSUE TITLE
Checklist for apply microservices development

### ISSUE THREAD

**Issue by ngtrdai197** [ngtrdai197/url-shortener#17]
- [x] Auth service
- [ ] Expiration service
- [ ] Teletegram Notify service
- [ ] Kafka (async event)
- [ ] gRPC (internal communication)
- [ ] Re-struct backend (core-service)
- [ ] Infra (k8s, Kong API)
